### ISSUE TITLE
WebGL Compute Support?

### ISSUE THREAD

**Issue by tsherif** [tsherif/picogl.js#131]
This would be a much larger update: https://www.khronos.org/registry/webgl/specs/latest/2.0-compute/

Not sure how much the API would have to change to support it and might want to wait until it stabilizes a bit.

Note: available in Chrome Canary behind the WebGL 2 compute flag.

**Comment by Shimmen** [comment]
Wow, great news to finally see it specified! Some initial thoughts in regards to PicoGL.js:

 - Shader creation doesn't have to change much except that a `createComputeProgram` or similar is required now.
 - Image load store is almost the best feature of all this! The binding process could work just like binding textures etc., but now memory barriers (e.g. `glMemoryBarrier(GL_SHADER_IMAGE_ACCESS_BARRIER_BIT)`) are relevant and have to be handled somehow. Maybe just `app.memoryBarrier(..)`?
 - As of now all setting of uniforms and textures happens on a draw call. For compute shaders we still need to set these things, but I'd argue that having draw calls for compute shaders doesn't make the most sense. I'd rather just call `computeProgram.dispatch(..)` directly. However, this would probably require a lot of the logic in `DrawCall` to be moved to `Program` or so.

It's probably wise to wait a little to implement it, as you said, since it's only a draft for now. On the other hand, it's probably not going to deviate much from the GL ES 3.1 specification... How long is it in general before they are finalized?

**Comment by tsherif** [comment]
Won't implement, since WebGL 2 Compute is being removed: https://www.khronos.org/webgl/public-mailing-list/public_webgl/2009/msg00000.php
