### ISSUE TITLE
Handling Context Lost

### ISSUE THREAD

**Issue by sjfricke** [tsherif/picogl.js#86]
After reviewing more closely the structure of the library I realized even with the App class keeping the gl state you would still need to recreate a lot of your classes (Example would be creating a new Framebuffer).

I guess I don't expect PicoGL to handle it all itself since its going to be application specific, and I know the browser will eventually come and clean out my unused constructed classes, but wondering if an example or helper functions to nuke stuff would be worth it as to my knowledge there are good and bad ways of efficiently handling restarting everything

**Comment by tsherif** [comment]
I agree that having any kind of automatic solution wouldn't really work with the design of PicoGL since it often involves things like re-downloading raw assets or storing them locally, which isn't within scope for PicoGL. 

One possible approach would be to add an optional `onContextLost` handler to each class. A PicoGL app could listen for context lost events and if one is triggered, loop through created resources and call their context lost handlers if they exist. Maybe classes should also have a `recreate` method or something like that to recreate the GL objects.

It might be a good idea to start with an example, like you suggested, to get a better idea of what the flow looks like when restoring resources after context loss.

**Comment by sjfricke** [comment]
Looking more into it, the nice part is there already are all the delete functions so 

```
var myFrameBuffer = createFramebuffer();
...
...

// on context lost
myFrameBuffer.delete()
delete myFrameBuffer;
```

So delete objects and clearing those resources shouldn't be bad

The app class would be nice to have an `onContextLost` for things like disabling things like `gl.BLEND`, `gl.DEPTH_TEST`, etc if they decide to recreate the App

**Comment by Shimmen** [comment]
If we were to keep it really light why not just have a function on the `App` object for deleting itself (and releasing all of its resources)? Then the user could handle it like:

```javascript
var app;

canvas.addEventListener("webglcontextlost", function(event) {

    event.preventDefault();
    app.delete();
    init();

}, false);

init();

function init() {

    app = PicoGL.createApp(canvas);
    // ... rest of setup code ...

}
```

Info about handling context loss can be found [here](https://www.khronos.org/webgl/wiki/HandlingContextLost).

**Comment by tsherif** [comment]
The thing to keep in mind is that deleting GL objects is not part of context loss recovery, since your handles to those objects will no longer be valid. The task is to re-initialize all objects using the new context. I'm thinking a way we could structure it is to have the App's `appState` property track created GL objects and to have all those objects contain on optional `onContextRestored` callback. If the context is lost and restored, the App would simply loop through all objects it has tracked and call their `onContextRestored` callback, allowing the application to do whatever it wants as a response.

Thoughts?

**Comment by tsherif** [comment]
I'm imagining a relatively bare-bones approach to this:
1. Separate out `init` method from constructors that actually initializes the object.
2. Expose an optional `app.onContextRestored` handler that is called if context is lost and restored. The application could use this handler to loop through all created objects and restore them using the init method and passing relevant data.

The reasoning is that I don't think PicoGL should be responsible for maintaining data cpu-side (e.g. shader source strings, geometry arrays), since the application might have a particular way it wants manage that data (e.g. gzipped). But that data is required for context recovery.
